### Update password
POST https://{{environment}}api.unleashed.be/{{brand}}/password/update
Authorization: Bearer {{token}}
Content-Type: application/json


{
    "new": "",
    "old": ""
}

### Initiate forgot password flow
POST https://{{environment}}api.unleashed.be/{{brand}}/password/reset/request
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "credentials": "jan.de.dobbeleer@gmail.com",
    "method": "MAIL",
    "recaptcha": "string"
}

### Reset your forgotten password
POST https://{{environment}}api.unleashed.be/{{brand}}/password/reset/perform
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "code": "string",
    "msisdn": "string",
    "password": "string"
}